"""R12 accepted-only Chicago figures from public saved vectors; no solver calls."""
from pathlib import Path
import argparse,json,sys
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from matplotlib.colors import PowerNorm
from matplotlib.ticker import ScalarFormatter,MaxNLocator,FuncFormatter
from style import new_figure,format_axes,export_figure,sha256,TEAL,BLUE,INK,ROAD,FLOW_CMAP,REPO

D=REPO/'docs'
def read(path):return json.loads(Path(path).read_text(encoding='utf-8'))
def source(path,role):return {'public_path':str(Path(path).relative_to(REPO)).replace('\\','/'),'sha256':sha256(path),'role':role}
def write_plot(stem,data):stem.with_suffix('.plot.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def render(output):
 output=Path(output);output.mkdir(parents=True,exist_ok=True);items=[]
 p=D/'assets/algorithm-transfer-r8/chicago/C06_S_convergence_plot_data.json';rows=read(p)['FW'];assert len(rows)==6
 x=np.array([int(r['iteration']) for r in rows]);y=np.array([float(r['objective']) for r in rows]);gap=np.array([float(r['relative_gap']) for r in rows]);assert list(x)==list(range(6))
 ref=D/'assets/plot-semantics-r9/chicago/s20-fw-map-distribution.plot_data.json';r=read(ref);assert r['independent']['status']=='ACCEPTED';assert abs(float(r['independent']['objective_saved'])-y[-1])<1e-10
 title='Frank–Wolfe: S20 objective and relative gap';fig=new_figure('chicago',title,figsize=(10,4.7));axes=fig.subplots(1,2);fig.subplots_adjust(left=.08,right=.98,bottom=.17,top=.76,wspace=.29)
 a,b=axes
 a.plot(x,y,color=BLUE,marker='o',markersize=4,linewidth=1.6);a.set(title='Beckmann objective',xlabel='Saved iteration',ylabel='Objective (PCE·min/h)');a.ticklabel_format(axis='y',style='plain',useOffset=False);a.yaxis.set_major_formatter(FuncFormatter(lambda v,p:f'{v:,.1f}'));a.set_ylim(y.min()-.22,y.max()+.25)
 b.semilogy(x,gap,color=TEAL,marker='o',markersize=4,linewidth=1.6,label='Saved full-graph gap');b.axhline(1e-5,color=INK,ls='--',lw=1,label='Frozen gate: $10^{-5}$');b.set(title='Full-graph stopping check',xlabel='Saved iteration',ylabel='Relative gap (dimensionless)');b.legend(loc='upper right',fontsize=8);b.set_ylim(1e-6,2e-2)
 for ax in axes:format_axes(ax);ax.set_xticks(x);ax.set_xlim(-.18,5.18)
 caption=('Accepted Chicago Jane Byrne / West Loop R2 S20 Frank–Wolfe run. All six actual saved states, iterations 0–5, are plotted without smoothing or invented samples. The Beckmann objective is PCE·min/h on the frozen one-hour 1,754.9482512397267 PCE/h demand. The full-graph relative gap ends at 3.446136191653708e-6, below the unchanged 1e-5 gate. The small rise between saved gaps at iterations 3 and 4 is retained. This S20 method history is distinct from the separate four-state full-city presentation record. Numerical results are engineering scenarios, not observed traffic.')
 stem=output/'chi-fw-history';rec={'figure_id':'R12-CHI-FW-HISTORY','city':'chicago','instance':'Chicago R2 S20;20 OD;1754.9482512397267 PCE/h','role':'iteration','saved_states':6,'conclusion':'The own FW objective and full-graph gap meet the original S20 gate at the saved endpoint.','panels':[{'quantity':'Beckmann objective','unit':'PCE·min/h'},{'quantity':'Full-graph relative gap','unit':'dimensionless'}],'quantity':['objective','full-graph relative gap'],'unit':['PCE·min/h','dimensionless'],'render_route':'Saved-data replot; selects only accepted FW records from the released mixed public data.','source_filter':{'key':'FW','saved_indices':[0,1,2,3,4,5]},'acceptance':r['independent'],'no_failed_attempts_displayed':True}
 sources=[source(p,'Six FW saved objective/gap states'),source(ref,'Independent accepted same-instance FW endpoint')];out=export_figure(fig,stem,rec,caption,sources);write_plot(stem,{'schema':'accepted-fw-history-v1','city':'chicago','instance':'R2 S20','rows':rows,'gate':1e-5,'unit':{'objective':'PCE·min/h','relative_gap':'dimensionless'}})
 items.append({'table_id':'chi-fw-history','originals':['assets/algorithm-transfer-r8/chicago/C06_S_convergence.svg'],'city':'chicago','title':title,'staged_stem':str(stem),'caption':caption,'source_hashes':sources,'route':rec['render_route'],'dimensions':out['dimensions'],'status':'RENDERED_PENDING_VISUAL_QA'})
 p=D/'assets/algorithm-transfer-r8/chicago/C06_T_physical_flow_plot_data.json';geo=D/'assets/plot-semantics-r9/chicago/fw-physical-flow.plot_data.json';status=D/'assets/algorithm-transfer-r8/CURRENT_STATUS.json';v=read(p);g=read(geo);receiver=next(r for r in read(status)['methods'] if r.get('city')=='chicago' and r.get('method')=='T_CG');assert receiver['receiver_status']=='ACCEPTED'
 ids=v['ordered_physical_ids'];flow=np.array(v['flow']['CG saved endpoint'],float);gids=g['physical_link_ids'];assert len(ids)==len(set(ids))==len(gids)==len(set(gids))==27129;assert set(ids)==set(gids);lookup=dict(zip(gids,g['display_segments_local_km']));segments=[lookup[k] for k in ids];assert len(flow)==len(segments);assert np.min(flow)>=0
 points=np.array([xy for seg in segments for xy in seg]);mins,maxs=points.min(0),points.max(0);ratio=(maxs[1]-mins[1])/(maxs[0]-mins[0]);positive=flow>0;norm=PowerNorm(gamma=.5,vmin=0,vmax=float(flow.max()));counts,edges=np.histogram(flow,bins=22,range=(0,float(flow.max())));assert int(counts.sum())==len(flow)
 title='Column generation: physical flow and distribution';fig=new_figure('chicago',title,figsize=(10,5.4));a=fig.add_axes([.07,.235,.4,.60]);b=fig.add_axes([.575,.235,.4,.60]);a.set_box_aspect(ratio);b.set_box_aspect(ratio)
 a.add_collection(LineCollection(segments,colors=ROAD,linewidths=.38,zorder=1));lc=LineCollection([segments[i] for i in np.flatnonzero(positive)],array=flow[positive],cmap=FLOW_CMAP,norm=norm,linewidths=1.2,zorder=3);a.add_collection(lc);pad=(maxs-mins)*.025;a.set_xlim(mins[0]-pad[0],maxs[0]+pad[0]);a.set_ylim(mins[1]-pad[1],maxs[1]+pad[1]);a.set(title='Own physical-link movement flow',xlabel='Local easting (km)',ylabel='Local northing (km)');format_axes(a,map_axis=True);a.xaxis.set_major_locator(MaxNLocator(5));a.yaxis.set_major_locator(MaxNLocator(5));cax=a.inset_axes([0,-.255,1,.035]);cb=fig.colorbar(lc,cax=cax,orientation='horizontal');cb.set_label('Physical-link pulse flow (PCE)',fontsize=9);cb.set_ticks([0,10,25,50]);cb.ax.tick_params(labelsize=8,length=2)
 b.bar(edges[:-1],counts,width=np.diff(edges),align='edge',color=TEAL,edgecolor='white',linewidth=.45,zorder=3);b.set(title='All physical-link flow values',xlabel='Physical-link pulse flow (PCE)',ylabel='Physical links (count)');b.set_xlim(0,float(flow.max()));b.set_ylim(0,max(counts)*1.075);b.yaxis.set_major_formatter(FuncFormatter(lambda value,pos:f'{value:,.0f}'));format_axes(b);b.text(.97,.96,f'{len(flow):,} physical links\n{int(np.count_nonzero(flow==0)):,} exact zeros',transform=b.transAxes,ha='right',va='top',fontsize=8,color=INK)
 caption=('Accepted Chicago R2 T4 column-generation endpoint on the original 30-second/H169 finite graph. The map sums this method’s own saved movement-arc flow over commodities and time onto each original physical-link ID; the unit is PCE in the selected pulse, not an hourly rate. The complete 27,129-link vector includes 26,597 exact zeros and 532 positive values. All physical links remain gray context, and positive links use a square-root sequential scale with original-unit colorbar ticks. The 22-bin histogram counts every physical link, including zeros, on a linear count axis. Public saved geometry is joined by a unique exact ID set; no static FW flow is reused. Ledger connectors are excluded. © OpenStreetMap contributors; road-derived data ODbL 1.0: https://www.openstreetmap.org/copyright. Numerical results are engineering scenarios, not observed traffic.')
 stem=output/'chi-cg-physical';rec={'figure_id':'R12-CHI-CG-PHYSICAL','city':'chicago','instance':receiver['instance'],'role':'spatial','conclusion':'Accepted CG own pulse flow is localized over a sparse subset of the retained physical road network.','panels':[{'quantity':'Own physical-link CG movement flow','unit':'PCE'},{'quantity':'All-link CG flow distribution','unit':'link count / PCE bins'}],'quantity':['Physical-link pulse flow','Physical-link counts'],'unit':['PCE','count'],'render_route':'Saved-data replot; approved CG flow joined to approved original physical geometry by exact unique persistent IDs.','geometry_join':{'flow_count':len(ids),'geometry_count':len(gids),'unique_id_sets_equal':True,'geometry_projected_crs':g['projected_crs'],'local_origin_projected_metres':g['local_origin_projected_metres'],'no_other_method_flow_read':True},'statistics':{'exact_zero':int(np.count_nonzero(flow==0)),'positive':int(positive.sum()),'minimum':float(flow.min()),'maximum':float(flow.max()),'histogram_count':int(counts.sum())},'acceptance':receiver,'no_failed_attempts_displayed':True}
 sources=[source(p,'Own CG physical-link pulse-flow vector; only CG saved endpoint selected'),source(geo,'Public physical geometry and coordinate system only; FW volume field unused'),source(status,'S0 accepted T_CG receiver status')];out=export_figure(fig,stem,rec,caption,sources);write_plot(stem,{'schema':'accepted-cg-physical-flow-v1','city':'chicago','instance':receiver['instance'],'ordered_physical_ids':ids,'cg_pulse_flow_pce':flow.tolist(),'display_segments_local_km':segments,'histogram':{'counts':counts.tolist(),'edges_pce':edges.tolist()},'projection':g['projected_crs'],'local_origin_projected_metres':g['local_origin_projected_metres']})
 items.append({'table_id':'chi-cg-physical','originals':['assets/algorithm-transfer-r8/chicago/C06_T_physical_flow.svg'],'city':'chicago','title':title,'staged_stem':str(stem),'caption':caption,'source_hashes':sources,'route':rec['render_route'],'dimensions':out['dimensions'],'status':'RENDERED_PENDING_VISUAL_QA'})
 manifest={'schema':'r12-accepted-mixed-render-v1','renderer':str(Path(__file__).relative_to(REPO)).replace('\\','/'),'solver_calls':0,'matcher_calls':0,'items':items}
 (output/'MIXED_RENDER_RESULT.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');return manifest
if __name__=='__main__':
 ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--output',type=Path,required=True);args=ap.parse_args();render(args.output)
