"""Restore released input-evidence graphics without importing private records."""
from pathlib import Path
import argparse,json,hashlib,csv,sys
from types import SimpleNamespace
import numpy as np
from style import new_figure,format_axes,export_figure,TEAL,BLUE,INK,sha256
from legacy_saved_figures import render_vector
REPO=Path(__file__).resolve().parents[2];D=REPO/'docs'
REG=json.loads((D/'assets/figure-contract-r11/DISPLAY_REGISTRY.json').read_text(encoding='utf8'))
def src(p):return {'public_path':p,'sha256':sha256(REPO/p)}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--output',type=Path,required=True);ap.add_argument('--pdf-package-dir',required=True);ap.add_argument('--pdf-python',default=sys.executable);ap.add_argument('--pdftoppm',default='pdftoppm');a=ap.parse_args()
 out=a.output;items=[]
 tid='ith-observation-bridge';t=REG['tables'][tid];data='docs/assets/gap-20261008/ithaca/ITH_GC02B_Observation_Counts.plot.csv';rows=list(csv.DictReader((REPO/data).open(encoding='utf8')));values=[int(r['source_link_count']) for r in rows];assert values==[60,21,6]
 title='Observation source links and network coverage';fig=new_figure('ithaca',title,'Saved input coverage / 87 source links',figsize=(9.4,4.6));ax=fig.add_subplot();fig.subplots_adjust(left=.25,right=.94,bottom=.18,top=.78)
 y=np.arange(3);ax.barh(y,values,color=[TEAL,BLUE,'#8797a2'],height=.56);ax.set_yticks(y,['R2 geometric candidates','Outside retained SCC','Access-filter exclusions']);ax.invert_yaxis();ax.set_xlim(0,70);ax.set_xticks(range(0,71,10));ax.set_xlabel('Source links (count)');format_axes(ax)
 for i,v in enumerate(values):ax.annotate(str(v),(v,i),xytext=(6,0),textcoords='offset points',va='center',fontsize=10)
 cap='Saved source-link coverage contains 87 records: 60 remain geometric R2 candidates, 21 have endpoints outside the retained strongly connected component, and 6 are excluded by access filtering. The latter 27 are unbridged. These are input coverage categories, not failed optimization runs. Candidate geometry does not establish an exact matched route, legal-turn validation, observed link flow or local calibration. All category counts come directly from the released aggregate CSV.'
 stem=out/'ithaca/observation-source-coverage';rec=export_figure(fig,stem,{'figure_id':'R12-ITH-OBS-SOURCE-COVERAGE','city':'ithaca','instance':'87 source links; released source-link coverage aggregate','role':'input-evidence','conclusion':'Sixty geometric candidates and 27 unbridged source links have separate source-coverage roles.','panels':{'a':'Released source-link coverage categories'},'quantity':'source-link category counts','unit':'source links'},cap,[src(data),src('docs/assets/gap-20261008/ithaca/ITH_GC02B_Observation_Counts.caption.txt')]);stem.with_suffix('.plot.json').write_text(json.dumps(rows,indent=2),encoding='utf8')
 items.append({'table_id':tid,'city':'ithaca','title':title,'staged_stem':str(stem),'originals':['assets/gap-20261008/ithaca/ITH_GC02B_Observation_Counts.png'],'caption':cap,'source_hashes':rec['sources'],'dimensions':rec['dimensions'],'status':'RENDERED_PENDING_VISUAL_QA'})
 tid='ith-counts-2022-summary';title='2022 observed counts and location evidence';original='docs/assets/gap-20261008/ithaca/ITH_GC06_Counts_2022.svg';caption=(D/'assets/gap-20261008/ithaca/ITH_GC06_Counts_2022.caption.txt').read_text(encoding='utf8').strip();caption+=' The scientific marks, source-direction symbols, axes and 51 plotted records are preserved exactly from the approved SVG. Only the outer typography and whitespace were adjusted. No underlying record CSV was reverse-engineered or published; these observed vehicle counts are not converted to PCE.'
 plan={'inventory_index':-12,'figure_id':'R12-ITH-2022-COUNTS','city':'ithaca','title':title,'caption':caption,'panels':{'a':'51 source-direction vehicle counts at 17 historical station codes','b':'3 source-coordinate records versus 48 station-ID-only records'},'render_method':'approved-vector-preservation','original_path':original,'original_sha256':sha256(REPO/original),'original_home_ids':[],'original_volume_anchors':[],'plot_data':['docs/assets/gap-20261008/ithaca/ITH_GC06_Counts_2022.caption.txt']}
 stem=out/'ithaca/observed-counts-2022';rec=render_vector(plan,stem,a);rec.update(figure_id='R12-ITH-2022-COUNTS',role='input-observations',instance='NYSDOT Region 03, source year 2022, 17 historical RCSTA codes',quantity='Vehicles in average weekday 11:00–12:00; source-record location evidence',unit='vehicles; source records',underlying_private_csv_reconstructed=False);stem.with_suffix('.source.json').write_text(json.dumps(rec,ensure_ascii=False,indent=2),encoding='utf8')
 items.append({'table_id':tid,'city':'ithaca','title':title,'staged_stem':str(stem),'originals':['assets/gap-20261008/ithaca/ITH_GC06_Counts_2022.png'],'caption':caption,'source_hashes':rec['sources'],'dimensions':rec['dimensions'],'scientific_geometry_preserved':rec['vector_geometry_preserved'],'render_method':'approved-vector-preservation','status':'RENDERED_PENDING_VISUAL_QA'})
 old='assets/city-alignment-r3/chicago-construction/input-time-layer-excerpt.svg';e=REG['figures'][old][0];cap=e['caption']+' Full frozen input graph: 1,351,628 arcs (876,268 movement, 475,122 waiting, 4 source connectors, 234 sink connectors). Four commodities total 66.53295454563035 PCE; all depart at step 5. Time step is 30 seconds and horizon H=169, or 84.5 minutes. These input dimensions supplement the shown time-layer excerpt and do not represent a solver result.'
 disposition={'table_id':'chicago-t4-construction','city':'chicago','action':'merge_metadata_into_existing_figure','existing_asset':e['src'],'existing_original':old,'existing_caption':e['caption'],'caption':cap,'title':e['title'],'originals':['assets/city-alignment-r3/chicago-construction/input-construction-ledger.svg'],'source_hashes':[src('docs/'+e['src']),src('docs/assets/city-alignment-r3/chicago-construction/input-construction-ledger.source.json')],'reason':'A real saved time-layer input figure already exists; its caption can carry the frozen graph dimensions without a duplicate count-only card.','status':'EXISTING_ASSET_VISUALLY_CHECKED'}
 result={'schema':'mcl-r12-input-supplement','items':items,'dispositions':[disposition],'solver_calls':0,'matcher_calls':0,'private_csv_reconstruction':False,'approved_original_bytes_preserved':True}
 out.parent.parent.joinpath('SUPPLEMENT_RENDER_RESULT.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf8');print(json.dumps({'figures':len(items),'dispositions':1}))
if __name__=='__main__':main()
